version: "3"
services:
  frontend:
    image: fakespot/fakespot.edu.pl:latest
    ports:
      - "8084:3000"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  frontend:
