version: "3"
services:
  web:
    image: fakespot/fakespot.edu.pl:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8084:3000"
    networks:
      - webnet
networks:
  webnet:
